install.packages("readr",lib="~/Rlib",repos="https://cloud.r-project.org/")
install.packages("dplyr",lib="~/Rlib",repos="https://cloud.r-project.org/")
install.packages("tidyr",lib="~/Rlib",repos="https://cloud.r-project.org/")
install.packages("crayon",lib="~/Rlib",repos="https://cloud.r-project.org/")
install.packages("utf8",lib="~/Rlib",repos="https://cloud.r-project.org/")
install.packages("cli",lib="~/Rlib",repos="https://cloud.r-project.org/")
